_format_version: "3.0"

services:
  - name: httpbin
    url: https://httpbin.kong.svc.cluster.local:8443
    tls_verify: true
    tls_verify_depth: 3
    ca_certificates:
      - id
    routes:
      - name: httpbin
        paths:
          - /httpbin
plugins:
  enabled: true
  name: prometheus
  config:
    upstream_health_metrics: true
    per_consumer: false
    bandwidth_metrics: true
    status_code_metrics: true
    wasm_metrics: false
    latency_metrics: true
    ai_metrics: false
  protocols:
    - grpc
    - grpcs
    - http
    - https